![NYC Skyline](nyc.jpg)

Welcome to New York City, one of the most-visited cities in the world. There are many Airbnb listings in New York City to meet the high demand for temporary lodging for travelers, which can be anywhere between a few nights to many months. In this project, we will take a closer look at the New York Airbnb market by combining data from multiple file types like `.csv`, `.tsv`, and `.xlsx`.

Recall that **CSV**, **TSV**, and **Excel** files are three common formats for storing data. 
Three files containing data on 2019 Airbnb listings are available to you:

**data/airbnb_price.csv**
This is a CSV file containing data on Airbnb listing prices and locations.
- **`listing_id`**: unique identifier of listing
- **`price`**: nightly listing price in USD
- **`nbhood_full`**: name of borough and neighborhood where listing is located

**data/airbnb_room_type.xlsx**
This is an Excel file containing data on Airbnb listing descriptions and room types.
- **`listing_id`**: unique identifier of listing
- **`description`**: listing description
- **`room_type`**: Airbnb has three types of rooms: shared rooms, private rooms, and entire homes/apartments

**data/airbnb_last_review.tsv**
This is a TSV file containing data on Airbnb host names and review dates.
- **`listing_id`**: unique identifier of listing
- **`host_name`**: name of listing host
- **`last_review`**: date when the listing was last reviewed

In [111]:
# Import necessary packages
import pandas as pd
import numpy as np

# Begin coding here ...
# Use as many cells as you like

In [112]:
airbnb_price = pd.read_csv('data/airbnb_price.csv')
airbnb_room_type = pd.read_excel('data/airbnb_room_type.xlsx')
airbnb_last_review = pd.read_csv('data/airbnb_last_review.tsv',sep='\t')

In [113]:
airbnb_price.head(10)

   listing_id        price                 nbhood_full
0        2595  225 dollars          Manhattan, Midtown
1        3831   89 dollars      Brooklyn, Clinton Hill
2        5099  200 dollars      Manhattan, Murray Hill
3        5178   79 dollars   Manhattan, Hell's Kitchen
4        5238  150 dollars        Manhattan, Chinatown
5        5295  135 dollars  Manhattan, Upper West Side
6        5441   85 dollars   Manhattan, Hell's Kitchen
7        5803   89 dollars       Brooklyn, South Slope
8        6021   85 dollars  Manhattan, Upper West Side
9        6848  140 dollars      Brooklyn, Williamsburg

In [114]:
airbnb_room_type.head()

   listing_id                                description        room_type
0        2595                      Skylit Midtown Castle  Entire home/apt
1        3831            Cozy Entire Floor of Brownstone  Entire home/apt
2        5099  Large Cozy 1 BR Apartment In Midtown East  Entire home/apt
3        5178            Large Furnished Room Near B'way     private room
4        5238         Cute & Cozy Lower East Side 1 bdrm  Entire home/apt

In [115]:
airbnb_last_review.head(20)

    listing_id         host_name      last_review
0         2595          Jennifer      May 21 2019
1         3831       LisaRoxanne     July 05 2019
2         5099             Chris     June 22 2019
3         5178          Shunichi     June 24 2019
4         5238               Ben     June 09 2019
5         5295              Lena     June 22 2019
6         5441              Kate     June 23 2019
7         5803            Laurie     June 24 2019
8         6021           Claudio     July 05 2019
9         6848     Allen & Irina     June 29 2019
10        7097              Jane     June 28 2019
11        7322              Doti     July 01 2019
12        7726  Adam And Charity     June 22 2019
13        8024             Lisel     July 01 2019
14        8025             Lisel  January 01 2019
15        8110             Lisel     July 02 2019
16        8490          Nathalie     June 19 2019
17        8505           Gregory     June 23 2019
18        9518              Shon     June 15 2019
19        9657              Dana    April 19 2019

In [116]:
airbnb_last_review.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25209 entries, 0 to 25208
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   listing_id   25209 non-null  int64
 1   host_name    25201 non-null  object
 2   last_review  25209 non-null  object
dtypes: int64(1), object(2)
memory usage: 591.0+ KB

In [117]:
airbnb_last_review.shape

(25209, 3)

In [118]:
airbnb_last_review['last_review'] = pd.to_datetime(airbnb_last_review['last_review'])

In [119]:
airbnb_last_review.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25209 entries, 0 to 25208
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   listing_id   25209 non-null  int64
 1   host_name    25201 non-null  object
 2   last_review  25209 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(1)
memory usage: 591.0+ KB

In [120]:
earlist_review_date = airbnb_last_review['last_review'].min()

In [121]:
earlist_review_date

Timestamp('2019-01-01 00:00:00')

In [122]:
recent_review_date = airbnb_last_review['last_review'].max()

In [123]:
recent_review_date

Timestamp('2019-07-09 00:00:00')

In [124]:
airbnb_room_type['room_type'] = airbnb_room_type['room_type'].astype('category')

In [125]:
airbnb_room_type['room_type'] = airbnb_room_type['room_type'].str.lower()

In [126]:
airbnb_room_type.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25209 entries, 0 to 25208
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   listing_id   25209 non-null  int64
 1   description  25199 non-null  object
 2   room_type    25209 non-null  object
dtypes: int64(1), object(2)
memory usage: 591.0+ KB

In [127]:
airbnb_room_type.groupby('room_type')['room_type'].count()

room_type
entire home/apt    13266
private room       11356
shared room          587
Name: room_type, dtype: int64

In [128]:
no_of_private_room = 11356

In [129]:
airbnb_price.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25209 entries, 0 to 25208
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   listing_id   25209 non-null  int64
 1   price        25209 non-null  object
 2   nbhood_full  25209 non-null  object
dtypes: int64(1), object(2)
memory usage: 591.0+ KB

In [130]:
airbnb_price['price'] = airbnb_price['price'].str.extract(r'(\d+)').astype(int)

In [131]:
airbnb_price.head(5)

   listing_id  price                nbhood_full
0        2595    225         Manhattan, Midtown
1        3831     89     Brooklyn, Clinton Hill
2        5099    200     Manhattan, Murray Hill
3        5178     79  Manhattan, Hell's Kitchen
4        5238    150       Manhattan, Chinatown

In [132]:
avg_price = round(airbnb_price['price'].agg(['mean']), 2)

In [133]:
print(avg_price)

mean    141.78
Name: price, dtype: float64

In [134]:
review_dates = pd.DataFrame({
    'first_reviewed' : earlist_review_date,
    'last_reviewed' : recent_review_date,
    'nb_private_rooms' : no_of_private_room,
    'avg_price' : avg_price
})

In [135]:
print(review_dates)

     first_reviewed last_reviewed  nb_private_rooms  avg_price
mean     2019-01-01    2019-07-09             11356     141.78